In [186]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_iris

In [187]:
iris = load_iris()
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [188]:
lr_scores = cross_val_score(LogisticRegression(solver='liblinear'), iris.data, iris.target)
lr_scores

array([1.        , 0.96666667, 0.93333333, 0.9       , 1.        ])

In [189]:
np.average(lr_scores)

0.9600000000000002

In [190]:
svm_scores = cross_val_score(SVC(), iris.data, iris.target)
svm_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [191]:
np.average(svm_scores)

0.9666666666666666

In [192]:
dt_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
dt_scores

array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])

In [193]:
np.average(dt_scores)

0.9533333333333334

In [194]:
rf_scores = cross_val_score(RandomForestClassifier(), iris.data, iris.target)
rf_scores

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [195]:
np.average(rf_scores)

0.96

In [196]:
print("Svm Score:                 ",np.average(svm_scores))
print("Decision Tree Score:       ",np.average(dt_scores))
print("Random Forest Score:       ",np.average(rf_scores))
print("Logistic Regression Score: ",np.average(lr_scores))

Svm Score:                  0.9666666666666666
Decision Tree Score:        0.9533333333333334
Random Forest Score:        0.96
Logistic Regression Score:  0.9600000000000002
