In [105]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits

In [106]:
digits = load_digits()
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [107]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [108]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [109]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target, test_size=0.3,random_state=42)

In [110]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

c:\Users\Raouf\anaconda3\envs\ML\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9648148148148148

In [111]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.987037037037037

In [112]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.975925925925926

In [113]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [114]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)


[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [115]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [116]:
get_score(LogisticRegression(), X_train, X_test, y_train, y_test)

c:\Users\Raouf\anaconda3\envs\ML\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9648148148148148

In [117]:
get_score(SVC(), X_train, X_test, y_train, y_test)

0.987037037037037

In [118]:
get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test)

0.9777777777777777

In [119]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [120]:
scores_lr =[]
scores_svm =[]
scores_rf =[]

for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index],digits.data[test_index] \
                                     , digits.target[train_index],digits.target[test_index]
    scores_lr.append(get_score(LogisticRegression(solver='liblinear'), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))


In [121]:
scores_lr

[0.8964941569282137, 0.9515859766277128, 0.9115191986644408]

In [122]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [123]:
scores_rf

[0.9348914858096828, 0.9565943238731218, 0.9332220367278798]

In [124]:
from sklearn.model_selection import cross_val_score

In [125]:
# cross_val_score(estimator=LogisticRegression(solver='liblinear'),X=digits.data,y=digits.target,cv=3) # By default cv = 5 (cv: cross_val_score)
cross_val_score(LogisticRegression(solver='liblinear'),digits.data,digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [126]:
cross_val_score(SVC(),digits.data,digits.target,cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [127]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target,cv=3)

array([0.93155259, 0.95993322, 0.92988314])

In [128]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target,cv=3) # n_estimators = 40

array([0.93155259, 0.94156928, 0.92320534])

In [129]:
cross_val_score(RandomForestClassifier(n_estimators=5),digits.data,digits.target,cv=3) # n_estimators = 5

array([0.84808013, 0.88146912, 0.87646077])