In [401]:
import pandas as pd
import numpy as np
from sklearn import datasets ,svm
iris = datasets.load_iris()

In [402]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [403]:
df = pd.DataFrame(iris.data,columns=iris.feature_names)
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x:iris.target_names[x])
df[47:52]

sepal length (cm)  sepal width (cm)  ...  petal width (cm)      flower
47                4.6               3.2  ...               0.2      setosa
48                5.3               3.7  ...               0.2      setosa
49                5.0               3.3  ...               0.2      setosa
50                7.0               3.2  ...               1.4  versicolor
51                6.4               3.2  ...               1.5  versicolor

[5 rows x 5 columns]

In [404]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3)

In [405]:
model = svm.SVC(kernel='rbf',C=30,gamma='auto')
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.9333333333333333

In [406]:
from sklearn.model_selection import cross_val_score

In [407]:
cross_val_score(svm.SVC(kernel='linear',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [408]:
cross_val_score(svm.SVC(kernel='rbf',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [409]:
cross_val_score(svm.SVC(kernel='rbf',C=20,gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [410]:
kernels = ['linear', 'rbf']
C = [1,10,20]
avg_score = {}
for kval in kernels:
    for cval in C:
        cv_score = cross_val_score(svm.SVC(kernel=kval, C=cval, gamma='auto'), iris.data, iris.target, cv=5)
        avg_score[kval + '_' + str(cval)] = np.average(cv_score) 

avg_score

{'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666,
 'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668}

In [411]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(svm.SVC(gamma='auto'), {
    'C':[1,10,20],
    'kernel':['linear', 'rbf'],
    },
    cv=5,
    return_train_score=False
)

clf.fit(iris.data,iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00167646, 0.00175319, 0.00130954, 0.00100799, 0.00140023,
        0.00140023]),
 'std_fit_time': array([4.71991947e-04, 7.27378639e-04, 4.05100756e-04, 1.65445316e-05,
        5.74757583e-04, 4.87494067e-04]),
 'mean_score_time': array([0.00100217, 0.00101171, 0.00081844, 0.00099974, 0.00080476,
        0.00115829]),
 'std_score_time': array([6.50074390e-06, 1.42522471e-05, 4.09750401e-04, 1.66824872e-06,
        4.02496028e-04, 4.77946241e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'linear'},
  {'C': 1, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C':

In [412]:
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.001676      0.000472  ...        0.016330                1
1       0.001753      0.000727  ...        0.016330                1
2       0.001310      0.000405  ...        0.038873                4
3       0.001008      0.000017  ...        0.016330                1
4       0.001400      0.000575  ...        0.042164                6
5       0.001400      0.000487  ...        0.036515                5

[6 rows x 15 columns]

In [413]:
df[['param_C', 'param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0        1       linear         0.980000
1        1          rbf         0.980000
2       10       linear         0.973333
3       10          rbf         0.980000
4       20       linear         0.966667
5       20          rbf         0.966667

In [414]:
dir(clf)

['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_estimator_type',
 '_format_results',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_routed_params_for_fit',
 '_get_scorers',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run

In [415]:
clf.best_score_

0.9800000000000001

In [416]:
clf.best_params_

{'C': 1, 'kernel': 'linear'}

In [417]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(svm.SVC(gamma='auto'), {
    'C':[1,10,20],
    'kernel':['linear', 'rbf'],
    },
    cv=5,
    return_train_score=False,
    n_iter=2
)

rs.fit(iris.data,iris.target)
pd.DataFrame(rs.cv_results_)[['param_C', 'param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       20          rbf         0.966667
1       20       linear         0.966667

In [418]:
rs.best_score_

0.9666666666666668

In [419]:
rs.best_params_

{'kernel': 'rbf', 'C': 20}

In [420]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [421]:
model_params = {
    'svm': {
        'model': svm.SVC(gamma= 'auto'),
        'params': {
            'C' : [1,10,20],
            'kernel': ['rbf', 'linear']
        }
    },
    'random_forest': {
        'model' : RandomForestClassifier(),
        'params': {
            'n_estimators': [1,5,10]
        }
    },
    'logistic_regression': {
        'model': LogisticRegression(solver='liblinear', multi_class='auto'),
        'params': {
        'C': [1,5,10]
        }
    }
}


In [422]:
scores = []

for model_name, mp in model_params.items():
    clf = GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(iris.data, iris.target)
    scores.append({
    'model' : model_name,
    'best_score' : clf.best_score_,
    'best_params': clf.best_params_
    })

c:\Users\Raouf\anaconda3\envs\ML\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\Raouf\anaconda3\envs\ML\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\Raouf\anaconda3\envs\ML\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
c:\Users\Raouf\anaconda3\envs\ML\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi

In [423]:
df = pd.DataFrame(scores,columns=['model', 'best_score', 'best_params'])
df                   

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.960000       {'n_estimators': 10}
2  logistic_regression    0.966667                   {'C': 5}